# Generated by Django 3.0.3 on 2020-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_auto_20200329_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_store',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
