# Generated by Django 3.0.3 on 2020-03-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_auto_20200329_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_of_addr',
            field=models.IntegerField(default=1),
        ),
    ]
