# Generated by Django 3.0.3 on 2020-03-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_auto_20200331_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
