# Generated by Django 3.0.3 on 2020-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_auto_20200331_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
